name: Jobs Tests
on: workflow_dispatch

jobs:
    validate-html:
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v4

            - name: validate html file
              run: test -f index.html

    validate-js:
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v4

            - name: validate js file
              run: test -f index.js
    
    validate-code:
        # needs: [validate-html, validate-js]  # This line indicates that the validate-code job depends on the successful completion of both validate-html and validate-js jobs.
        needs: [validate-html, validate-js]
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v4

            - name: validate js code
              run: node --check index.js
            
            - name: validate html code
              run: npx htmlhint index.html